-- 0002 — causal ordering.
--
-- 0001 ordered events by (occurred_at, recorded_at, event_id). An integration test caught
-- why that is wrong: a client submitting a batch produces events sharing one millisecond,
-- and `now()` is transaction-time in Postgres, so recorded_at is identical across a single
-- INSERT too. Ordering then fell to event_id — a random uuid. The fold was deterministic
-- but causally wrong, folding `triaged` after `overridden` and losing the override.
--
-- Determinism was never the hard part. Causality is.
--
-- Two columns fix it, for two different reasons:
--
--   client_seq  the client's own ordering of events it created. Preserves causality
--               within one device's offline batch, which is exactly the case that
--               matters most (ADR-0002).
--
--   seq         server arrival order. A stable final tiebreaker between independent
--               clients, and the correct sync cursor — a timestamp cursor can silently
--               skip events that share a recorded_at, which is the same bug wearing a
--               different hat.
--
-- Forward-only, per the discipline in src/db/pool.ts: 0001 is not edited, 0002 corrects it.

BEGIN;

ALTER TABLE incident_event
    ADD COLUMN IF NOT EXISTS seq        bigint GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS client_seq integer NOT NULL DEFAULT 0;

-- Backfill: existing rows keep a stable order under the new comparator.
UPDATE incident_event SET client_seq = 0 WHERE client_seq IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS incident_event_seq ON incident_event (seq);

-- The fold's read path, in its exact order.
DROP INDEX IF EXISTS incident_event_by_incident;
CREATE INDEX incident_event_by_incident
    ON incident_event (incident_id, occurred_at, client_seq, recorded_at, seq);

-- The sync cursor. Replaces the recorded_at index, which could not be paged safely.
DROP INDEX IF EXISTS incident_event_by_recorded;
CREATE INDEX incident_event_by_seq ON incident_event (seq);

INSERT INTO schema_migration (version) VALUES ('0002_event_ordering')
ON CONFLICT (version) DO NOTHING;

COMMIT;
